import Link from "@/components/site-link";
import { CaseSpotlight, ClientCases } from "@/components/client-cases";
import { WhatsAppButton } from "@/components/whatsapp";
import { ArrowUpRight, ArrowRight, ScanLine, Workflow, Search, GraduationCap, Mail, FileText, RotateCcw, Check } from "lucide-react";
import { CTA, Tick } from "@/components/site-shell";
import { absolute } from "@/lib/site";
import { BusinessOffers, TrainingPrograms } from "@/components/offer-sections";
export const metadata={alternates:{canonical:absolute('/')}};
export default function Home(){return <main id="main">
<section className="wrap hero"><div className="hero-copy"><p className="eyebrow"><span className="tiny-cross">+</span> CONSEIL & AUTOMATISATION IA · PAYS BASQUE</p><h1>Moins de tâches.<br/>Plus de <span className="serif-word">métier.</span></h1><p className="hero-intro">Votre entreprise mérite mieux que des heures de copier-coller. On diagnostique vos processus, on construit les bons systèmes, vous reprenez la main.</p><div className="hero-actions"><Link className="button" href="/services/audit-ia">Mon diagnostic IA — 99 € <ArrowUpRight size={19}/></Link><WhatsAppButton/></div><p className="hero-note">Pour les TPE & PME de Bayonne, Anglet et Biarritz.</p></div>
<CaseSpotlight/></section>
<ClientCases/>
<div className="principles"><div className="wrap principles-inner"><span>Du concret, dès le départ.</span><span><Check size={16}/> Vos outils, connectés</span><span><Check size={16}/> Vos décisions, préservées</span><span><Check size={16}/> Des résultats, mesurés</span></div></div>
<section className="wrap section"><div className="section-heading"><div><p className="eyebrow">01 / LES SYMPTÔMES</p><h2>Ça vous prend du temps.<br/>Tous les jours.</h2></div><p>Partons de votre quotidien.<br/>La technologie vient ensuite.</p></div><div className="problem-grid">{[{n:'01',icon:FileText,title:'Les devis après la journée.',text:'Retrouver les infos, reprendre un modèle, tout ressaisir. Et recommencer.',url:'automatiser-devis',cta:'Préparer mes devis'},{n:'02',icon:RotateCcw,title:'Les relances « demain ».',text:'Des devis envoyés, des prospects sans nouvelles et aucun rappel au bon moment.',url:'automatiser-relances',cta:'Organiser mes relances'},{n:'03',icon:Mail,title:'La boîte mail déborde.',text:'Trier, transférer, répondre aux mêmes questions. Votre vrai travail attend.',url:'automatiser-emails',cta:'Mieux traiter mes emails'}].map(x=><Link key={x.n} href={'/solutions/'+x.url} className="problem-card"><div className="card-top"><x.icon size={24}/><span>{x.n}</span></div><h3>{x.title}</h3><p>{x.text}</p><span className="card-link">{x.cta}<ArrowUpRight size={18}/></span></Link>)}</div></section>
<section className="dark-section"><div className="wrap section"><div className="section-heading"><div><p className="eyebrow">02 / LA MÉTHODE MISTER IA 64</p><h2>On comprend avant<br/>de <span className="serif-word">construire.</span></h2></div><Link className="text-link" href="/methode">Notre méthode en détail <ArrowUpRight size={18}/></Link></div><div className="method-grid">{[['01','Comprendre','On observe un processus réel et on identifie ce qui vous ralentit.'],['02','Cadrer','On priorise les pistes et on chiffre un pilote adapté à vos moyens.'],['03','Construire','On teste avec votre équipe et on documente.'],['04','Suivre','On mesure l’usage, le temps gagné et les corrections nécessaires.']].map(x=><div key={x[0]}><span className="step-num">{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div><p className="dark-note">L’IA quand elle est utile. Une automatisation simple quand elle suffit.</p></div></section>
<section className="wrap section"><div className="section-heading"><div><p className="eyebrow">03 / LES EXPERTISES</p><h2>Du premier diagnostic<br/>au système qui tourne.</h2></div><Link className="text-link" href="/services">Toutes les expertises <ArrowUpRight size={18}/></Link></div><div className="expertise-grid">{[{icon:ScanLine,t:'Diagnostic IA',d:'Un processus analysé, 3 à 5 pistes et une recommandation de pilote.',price:'99 €',href:'audit-ia'},{icon:Workflow,t:'Automatisation & agents IA',d:'Des outils qui se parlent et des tâches qui avancent, avec vos règles.',price:'Sur devis',href:'automatisation-ia'},{icon:Search,t:'Visibilité SEO & GEO',d:'Une présence claire et crédible sur Google et les moteurs de recherche IA.',price:'Sur devis',href:'seo-geo'},{icon:GraduationCap,t:'Formation de vos équipes',d:'Des ateliers sur vos usages, pour savoir faire et garder le contrôle.',price:'Sur devis',href:'formation-ia'}].map(x=><Link href={'/services/'+x.href} className="expertise-card" key={x.t}><x.icon size={25}/><h3>{x.t}</h3><p>{x.d}</p><div><span>{x.price}</span><ArrowUpRight size={21}/></div></Link>)}</div></section>
<section className="wrap diagnosis-section"><div><p className="eyebrow">UNE DÉCISION ÉCLAIRÉE</p><h2>Avant d’investir dans l’IA,<br/>investissez dans la clarté.</h2><p>Le diagnostic se concentre sur un processus prioritaire. Vous repartez avec une lecture claire des frictions et un plan exploitable, même si vous choisissez de vous arrêter là.</p><Link className="text-link" href="/services/audit-ia">Voir le périmètre du diagnostic <ArrowRight size={17}/></Link></div><div className="price-card"><div className="price-top"><span>DIAGNOSTIC IA</span><ScanLine size={23}/></div><p className="price">99 €</p><p>Un processus. Un livrable concret.</p><ul className="ticks"><Tick>Entretien et observation de votre fonctionnement</Tick><Tick>3 à 5 opportunités classées par intérêt</Tick><Tick>Un pilote recommandé et un budget estimatif</Tick><Tick>Restitution et prochaines étapes</Tick></ul><Link href="/contact?offre=diagnostic" className="button">Demander mon diagnostic <ArrowUpRight size={18}/></Link><p className="small-text">Cadrage et devis avant engagement. Aucun paiement en ligne.</p></div></section>
<section className="wrap local-section"><p className="eyebrow">UN INTERLOCUTEUR, PRÈS DE VOUS</p><h2>Ancré au Pays Basque.<br/>Branché sur votre réalité.</h2><div className="local-bottom"><p>Un atelier dans vos locaux, un processus observé avec votre équipe, puis un suivi à distance. Nous intervenons sur le BAB et la Côte Basque selon le périmètre convenu.</p><Link className="text-link" href="/pays-basque">Notre zone d’intervention <ArrowUpRight size={18}/></Link></div><div className="city-line"><span>Bayonne</span><span>Anglet</span><span>Biarritz</span><span>Pays Basque</span></div></section>
<BusinessOffers/>
<TrainingPrograms compact/>
<div className="wrap"><CTA/></div></main>}
