import Image from "next/image";
import { ArrowUpRight } from "lucide-react";
import Link from "@/components/site-link";

export function MarketplaceLogos() {
  return <div className="marketplace-logos" aria-label="Plateformes concernées par la migration"><Image src="/logos/rakuten.svg" alt="Rakuten" width={105} height={32}/><span aria-hidden="true">→</span><span>Boutique indépendante</span><span aria-hidden="true">+</span><Image src="/logos/amazon.svg" alt="Amazon" width={96} height={32}/></div>;
}

export function CaseSpotlight() {
  return <div className="process-card client-spotlight"><p className="eyebrow">CAS CLIENT · BELA LUGOSI</p><h2>15 000 références.<br/>Une activité qui continue.</h2><p>Un catalogue à sortir de Rakuten. Un bot pour récupérer les annonces, associer les photos et préparer la suite.</p><MarketplaceLogos/><div className="case-highlight"><strong>Vendre, plutôt que tout ressaisir.</strong><p>Catalogue importé dans sa propre boutique, tarification assistée et import sur Amazon.</p></div><div className="case-foot"><span>Du travail manuel à l’automatisation.</span><Link href="#bela-lugosi" aria-label="Découvrir le cas Bela Lugosi"><ArrowUpRight size={22}/></Link></div></div>;
}

const cases = [
  { id: "bela-lugosi", name: "Bela Lugosi", category: "E-COMMERCE · MIGRATION DE CATALOGUE", title: "Changer de boutique sans repartir de zéro.", metric: "15 000 références", result: "Un catalogue transféré, une activité maintenue.", problem: "Sa boutique Rakuten devait fermer en fin d’année. Sans export de catalogue exploitable à sa disposition, il faisait face à la reprise manuelle de 15 000 fiches produits.", solution: "Nous avons créé un bot pour récupérer les annonces, les photos et les descriptions. Puis nous avons construit sa propre boutique et automatisé l’import des références : association des bonnes images, tarification intelligente et import sur Amazon.", outcome: "Il peut continuer à vendre pendant la transition. Le travail manuel évité est estimé par le client à deux années de saisie.", link: "/services/automatisation-ia", cta: "Automatiser mon catalogue" },
  { id: "amina", name: "Société AMINA", category: "ARTISANAT · ASSISTANT VOCAL", title: "Sur le chantier, sans laisser les appels sans réponse.", metric: "≈ 10 appels manqués / semaine", result: "Le point de départ : des demandes perdues pendant les chantiers.", problem: "Souvent sur chantier dans une zone mal couverte, le dirigeant ratait environ dix appels par semaine. Lorsqu’il rappelait, le prospect avait souvent déjà trouvé un artisan disponible.", solution: "Nous avons mis en place un assistant vocal IA utilisant la voix du dirigeant. Il accueille les appels, recueille le nom, le prénom et les précisions sur le projet, puis propose et réserve une visite de chantier selon les disponibilités du calendrier.", outcome: "Les demandes sont qualifiées et les visites organisées pendant que le dirigeant travaille. Selon son estimation, un seul client gagné suffit à couvrir le coût de la solution.", link: "/services/agents-ia", cta: "Mieux accueillir mes appels" },
  { id: "noxvault", name: "NOXVAULT Ltd", category: "E-COMMERCE · CONTENUS & PUBLICITÉS", title: "Le matin, des créations déjà prêtes à valider.", metric: "Images + vidéos", result: "De l’analyse des publicités à la préparation des prochaines créations.", problem: "Cette société britannique consacrait beaucoup de temps aux fiches produits, aux pages de vente et surtout à la création des publicités.", solution: "Nous avons créé un système qui analyse ses publicités les plus performantes, identifie les angles à retravailler et prépare de nouvelles variantes. L’agent recherche aussi des produits adaptés à la boutique et prépare leur intégration avec les contenus de marque.", outcome: "Au réveil, le dirigeant retrouve des publicités images et vidéos prêtes à valider. Après son accord, leur publication est automatisée sur les canaux publicitaires utilisés.", link: "/services/marketing-reseaux-sociaux", cta: "Organiser ma production marketing" },
  { id: "pomas", name: "Pomas", category: "AIDE AUX SINISTRÉS · DÉMARCHES SIMPLIFIÉES", title: "Après la tempête, rendre les démarches plus accessibles.", metric: "Une adresse comme point de départ", result: "Moins de recherches et de ressaisies pour les habitants.", problem: "Après la tempête, les sinistrés devaient préparer leurs documents et retrouver leurs références cadastrales. Des démarches difficiles pour les personnes peu à l’aise avec les outils administratifs en ligne.", solution: "Nous avons créé un site où les habitants renseignent leurs informations pour préparer les documents et formulaires Cerfa. L’outil retrouve les références cadastrales à partir de l’adresse, sans leur imposer une recherche séparée.", outcome: "Les habitants, jeunes comme âgés, peuvent préparer leurs dossiers plus simplement. Les informations préremplies restent à vérifier avant l’envoi des documents aux organismes concernés.", link: "/services/automatisation-ia", cta: "Simplifier un parcours administratif" },
];

export function ClientCases({ auditFocus = false }: { auditFocus?: boolean }) {
  return <section className="wrap section client-cases" id="realisations" aria-labelledby="cases-title"><div className="section-heading"><div><p className="eyebrow">DES SITUATIONS CONCRÈTES</p><h2 id="cases-title">Des tâches qui bloquaient.<br/>Des solutions mises en place.</h2></div><p>Un catalogue, des appels, des publicités,<br/>des démarches : l’IA part du besoin réel.</p></div><div className="client-case-grid">{cases.map(c=><article className="client-case-card" id={c.id} key={c.id}><p className="eyebrow">{c.category}</p><p className="client-name">{c.name}</p><h3>{c.title}</h3><div className="client-result"><strong>{c.metric}</strong><p>{c.result}</p></div><details><summary>Découvrir le projet</summary><h4>Avant</h4><p>{c.problem}</p><h4>Ce que nous avons mis en place</h4><p>{c.solution}</p><h4>Ce que cela change</h4><p>{c.outcome}</p>{c.id==='bela-lugosi'&&<MarketplaceLogos/>}</details><Link className="text-link" href={auditFocus ? "#audit" : c.link}>{auditFocus ? "Identifier les possibilités chez moi" : c.cta}<ArrowUpRight size={17}/></Link></article>)}</div></section>;
}
