import Link from "@/components/site-link";
import { WhatsAppButton } from "@/components/whatsapp";
import { AuditButton } from "@/components/audit-button";
import { Activity, ArrowUpRight, Check } from "lucide-react";
export function Brand(){return <Link href="/" className="brand" aria-label="Mister IA 64 — accueil"><span className="brand-mark"><Activity size={24}/></span>Mister <span className="brand-ia">IA</span><span className="brand-64"> 64</span></Link>}
export function Header(){return <header className="header"><div className="wrap header-inner"><Brand/><nav className="desktop-nav" aria-label="Navigation principale"><Link href="/services">Expertises</Link><Link href="/solutions">Vos besoins</Link><Link href="/services/formation-ia">Formations</Link><Link href="/methode">La méthode</Link><Link href="/guides">Ressources</Link></nav><AuditButton className="button small header-cta">Mon audit personnalisé</AuditButton><details className="mobile-menu"><summary>Menu</summary><nav aria-label="Navigation mobile"><Link href="/services">Expertises</Link><Link href="/solutions">Vos besoins</Link><Link href="/services/formation-ia">Formations</Link><Link href="/methode">La méthode</Link><Link href="/guides">Ressources</Link><Link href="/contact">Contact</Link><AuditButton className="text-link">Mon audit personnalisé — 99 €</AuditButton><WhatsAppButton className="text-link"/></nav></details></div></header>}
export function Footer(){return <footer><div className="wrap footer-grid"><div><Brand/><p>L’IA appliquée à votre quotidien.<br/>Bayonne · Anglet · Biarritz · Pays Basque</p><p className="small-text">Conseil aux entreprises. Aucune prestation médicale.</p></div><div><strong>Votre prochain pas</strong><Link href="/services/audit-ia">Diagnostic IA — 99 €</Link><Link href="/diagnostic">Estimer mon potentiel</Link><Link href="/contact">Parler de mon besoin</Link><WhatsAppButton className="text-link"/></div><div><strong>Mister IA 64</strong><Link href="/guides">Guides IA pour dirigeants</Link><Link href="/services">Services IA pour les entreprises</Link><Link href="/a-propos">À propos</Link><Link href="/pays-basque">Interventions au Pays Basque</Link><Link href="/securite">Données & confidentialité</Link></div></div><div className="wrap footer-bottom"><span>© 2026 Mister IA 64</span><Link href="/mentions-legales">Mentions légales</Link><Link href="/confidentialite">Confidentialité</Link></div></footer>}
export function CTA({compact=false}:{compact?:boolean}){return <section className={compact?'cta-panel compact':'cta-panel'}><div><p className="eyebrow">LE PREMIER PAS</p><h2>On regarde où<br/>vous perdez du temps ?</h2><p>Un processus. Un diagnostic. Un plan concret pour avancer.</p></div><div><Link className="button" href="/services/audit-ia">Découvrir le diagnostic — 99 € <ArrowUpRight size={18}/></Link><WhatsAppButton/></div></section>}
export function Tick({children}:{children:React.ReactNode}){return <li><Check size={17}/><span>{children}</span></li>}
