import type { ContentPage } from "./content";

export const businessOffers = [
  { title: "Marketing & réseaux sociaux", text: "Un calendrier éditorial, des contenus préparés avec l’IA et des publications programmées après votre validation.", href: "/services/marketing-reseaux-sociaux", icon: "marketing" },
  { title: "Rendez-vous & plannings", text: "Des créneaux faciles à réserver, des confirmations et des rappels. Votre agenda reste la référence.", href: "/services/gestion-plannings", icon: "calendar" },
  { title: "Blog & contenus SEO", text: "Des articles utiles à vos clients, préparés avec l’IA, relus et publiés selon un rythme adapté à votre activité.", href: "/services/blog-automatise", icon: "blog" },
  { title: "Chatbots & agents vocaux", text: "Accueillir les demandes, répondre aux questions courantes et qualifier les prospects avant de passer la main.", href: "/services/agents-ia", icon: "agent" },
  { title: "Facturation & relances", text: "Relier vos outils pour préparer les factures, suivre les échéances et relancer avec le bon contexte.", href: "/services/facturation-relances", icon: "invoice" },
] as const;

export const trainingTracks = [
  { id: "outils-livres", title: "Prendre en main vos outils livrés", audience: "Pour les équipes qui utilisent une solution que nous avons installée.", text: "Utiliser le système au quotidien, vérifier ses résultats, modifier les réglages courants et réagir quand un cas sort du cadre.", exercise: "Réaliser un cas complet dans votre outil, puis traiter une exception avec un guide de prise en main.", icon: "tools" },
  { id: "images-videos", title: "Créer des images & vidéos marketing", audience: "Pour les dirigeants, commerçants et équipes communication.", text: "Passer d’une idée à un brief, générer des visuels cohérents avec votre marque et préparer une vidéo courte pour vos campagnes ou réseaux sociaux.", exercise: "Produire un visuel et un premier montage court à partir du même brief, puis vérifier leur qualité et les conditions d’utilisation des éléments employés.", icon: "image" },
  { id: "sites-web", title: "Créer un site web avec l’IA", audience: "Pour les indépendants et équipes qui veulent créer ou faire évoluer leur site.", text: "Structurer les pages, rédiger une offre claire, construire une première version avec l’IA et préparer la mise en ligne.", exercise: "Construire une page de présentation, contrôler son affichage mobile et suivre une liste de vérifications avant publication.", icon: "web" },
  { id: "ia-quotidien", title: "Utiliser l’IA au quotidien", audience: "Pour débuter sur des tâches administratives, commerciales ou de gestion.", text: "Rédiger des emails, synthétiser des documents, préparer un rendez-vous et réutiliser des consignes adaptées à votre métier.", exercise: "Créer trois modèles de travail réutilisables et apprendre à vérifier les réponses obtenues.", icon: "daily" },
  { id: "premieres-automatisations", title: "Créer ses premières automatisations", audience: "Pour les utilisateurs à l’aise avec leurs outils numériques.", text: "Relier un formulaire, un tableau ou un agenda. Comprendre les déclencheurs, les conditions et les reprises en cas d’erreur.", exercise: "Construire et tester un circuit simple, avec une étape de validation et une procédure d’arrêt.", icon: "automation" },
] as const;

const service = (index: number, title: string, sections: ContentPage["sections"], links: string[], faq: ContentPage["faq"]): ContentPage => ({ path: businessOffers[index].href, kicker: businessOffers[index].title.toUpperCase() + " · SUR DEVIS", title, lead: businessOffers[index].text, sections, links, faq, price: null, kind: "service", sources: [] });

export const additionalServices: ContentPage[] = [
  service(0, "Votre communication avance. Même les semaines chargées.", [
    { title: "Partir de ce que vos clients veulent savoir", paragraphs: ["Vos réalisations, vos réponses aux questions fréquentes et vos offres deviennent une base de contenus. Nous définissons ensemble les sujets et le rythme. L’IA prépare des propositions ; votre expertise leur donne leur valeur."], items: ["Calendrier éditorial adapté à vos moyens.", "Brouillons de publications et propositions de visuels.", "Déclinaisons pour les réseaux retenus au cadrage."] },
    { title: "Valider, programmer, suivre", paragraphs: ["Une étape de relecture précède la programmation. Les connexions à vos comptes sont vérifiées selon les possibilités de chaque plateforme. Vous pouvez corriger ou suspendre une publication. Les réponses automatiques aux commentaires et messages privés ne font pas partie du périmètre par défaut."], items: ["Circuit de validation identifié.", "Programmation sur les canaux compatibles.", "Suivi des publications et des demandes attribuables."] },
    { title: "Un service ajusté à votre rythme", paragraphs: ["Le devis précise les canaux, les volumes, les corrections et les abonnements éventuels. La gestion des publicités et de leur budget fait l’objet d’un périmètre distinct. Aucun nombre de prospects n’est garanti."], items: [] },
  ], ["/services/formation-ia#images-videos", "/services/blog-automatise", "/contact"], [{ q: "Dois-je encore intervenir ?", a: "Oui. Vous validez les informations, le ton et les contenus avant diffusion. Le système vous aide à tenir un rythme tout en gardant votre regard métier." }]),
  service(1, "Moins d’allers-retours. Des rendez-vous mieux organisés.", [
    { title: "Des créneaux qui respectent votre organisation", paragraphs: ["Durée, déplacements, horaires et personnes disponibles : nous commençons par vos règles. Les réservations s’appuient sur un agenda de référence pour limiter les doubles saisies et les conflits."], items: ["Parcours de réservation selon le type de rendez-vous.", "Synchronisation avec les agendas compatibles.", "Temps de battement et plages indisponibles."] },
    { title: "Confirmer et rappeler au bon moment", paragraphs: ["Les clients retrouvent les informations utiles et comment déplacer ou annuler leur rendez-vous. Les messages et leurs horaires sont définis ensemble. Nous testons les annulations et les indisponibilités, pas seulement une réservation réussie."], items: ["Confirmations et rappels selon les canaux retenus.", "Gestion des modifications et annulations.", "Signalement des cas non traités à votre équipe."] },
    { title: "Un périmètre clair avant la mise en place", paragraphs: ["Le devis précise les agendas, les rendez-vous, les canaux et les coûts des outils ou messages. Nous suivons les ressaisies et les conflits ; les rappels ne garantissent pas la présence de chaque client."], items: [] },
  ], ["/services/agents-ia", "/services/automatisation-ia", "/contact"], [{ q: "Peut-on garder notre agenda actuel ?", a: "Nous vérifions d’abord ses possibilités de connexion. Un nouvel outil n’est proposé que si votre fonctionnement le nécessite." }]),
  service(2, "Un blog qui répond à vos clients. Et tient dans votre planning.", [
    { title: "Des sujets ancrés dans votre activité", paragraphs: ["Les questions de vos clients et vos services guident le calendrier. Chaque article répond à une intention précise. Vos exemples, vos méthodes et vos informations locales nourrissent le contenu."], items: ["Choix des sujets et briefs éditoriaux.", "Recherche de sources et informations à confirmer.", "Structure des articles et liens vers les pages utiles."] },
    { title: "Préparer, relire, publier", paragraphs: ["L’IA prépare un brouillon. Les informations, les sources et la pertinence métier sont vérifiées avant publication. Le circuit sépare brouillon, validation et programmation dans votre outil de gestion de contenu."], items: ["Brouillons relus et corrigés.", "Titres, descriptions et maillage interne.", "Publication après validation sur un site compatible."] },
    { title: "Suivre la qualité dans la durée", paragraphs: ["Le devis définit la fréquence, le volume, la relecture et la maintenance des contenus. Nous suivons les pages consultées et les demandes utiles. Aucun volume de publications ne garantit une place sur Google ou une citation par une IA."], items: [] },
  ], ["/services/seo-geo", "/services/marketing-reseaux-sociaux", "/contact"], [{ q: "Les articles sont-ils publiés sans relecture ?", a: "Le circuit prévu inclut une validation avant publication. Les contenus doivent refléter votre activité et contenir des informations vérifiées." }]),
  service(4, "Vos factures suivies. Vos relances au bon moment.", [
    { title: "De la prestation à la facture à valider", paragraphs: ["Devis accepté, prestation terminée ou échéance convenue : nous identifions ce qui déclenche la préparation. Les informations sont reprises dans votre logiciel de facturation compatible, puis contrôlées avant émission."], items: ["Récupération des informations sans ressaisie.", "Préparation dans votre logiciel de facturation.", "Validation des montants et des informations de facturation."] },
    { title: "Relancer avec le bon contexte", paragraphs: ["Les scénarios suivent l’échéance et le statut de paiement disponible dans l’outil de référence. Les clients ayant payé sont exclus lorsque le paiement est confirmé. Les litiges et les dossiers particuliers passent à votre équipe."], items: ["Rappels définis selon vos règles et votre ton.", "Arrêt après confirmation du paiement.", "Mise en pause manuelle et suivi des exceptions."] },
    { title: "Un circuit testé avec votre équipe", paragraphs: ["Nous testons les paiements partiels, les retards de synchronisation et les doublons. Le devis précise les logiciels, les scénarios, les coûts récurrents et la maintenance. Ce suivi ne garantit pas le recouvrement des créances et ne remplace pas votre conseil comptable."], items: [] },
  ], ["/solutions/automatiser-relances", "/solutions/automatiser-devis", "/contact"], [{ q: "L’IA décide-t-elle des montants ?", a: "Non. Les montants viennent de vos données validées. Les changements engageants demandent une validation humaine." }]),
];
