import Link from "@/components/site-link";
import { notFound } from "next/navigation";
import { ArrowUpRight, ChevronRight } from "lucide-react";
import { pages, findPage } from "@/lib/content";
import { absolute, site } from "@/lib/site";
import { CTA } from "@/components/site-shell";
const hubs:Record<string,{title:string;lead:string;kind:string}>= {'/services':{title:'De quoi votre entreprise a-t-elle besoin ?',lead:'Diagnostiquer, connecter les outils, former l’équipe ou améliorer votre visibilité. Un périmètre clair pour chaque intervention.',kind:'service'},'/solutions':{title:'Partons de ce qui vous ralentit.',lead:'Des situations concrètes pour repérer un premier processus à améliorer. Les scénarios décrits sont illustratifs et s’adaptent à votre fonctionnement.',kind:'solution'},'/guides':{title:'Comprendre avant de décider.',lead:'Des méthodes concrètes pour évaluer un projet et poser les bonnes questions. Aucun chiffre de résultat client inventé.',kind:'guide'}};
export function generateStaticParams(){return [...pages.map(p=>p.path),...Object.keys(hubs)].map(p=>({slug:p.slice(1).split('/')}))}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}){const path='/'+(await params).slug.join('/');const p=findPage(path)||hubs[path];if(!p)return {title:'Page introuvable',robots:{index:false,follow:false}};return {title:p.title,description:p.lead,alternates:{canonical:absolute(path)},openGraph:{title:p.title,description:p.lead,url:absolute(path)},twitter:{card:'summary',title:p.title,description:p.lead}}}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const path='/'+(await params).slug.join('/');const p=findPage(path),hub=hubs[path];if(!p&&!hub)notFound();const title=(p||hub).title;const parent=path.startsWith('/services/')?'/services':path.startsWith('/solutions/')?'/solutions':path.startsWith('/guides/')?'/guides':null;const crumb=[{name:'Accueil',item:absolute('/')},...(parent?[{name:hubs[parent].kind==='service'?'Expertises':hubs[parent].kind==='solution'?'Solutions':'Guides',item:absolute(parent)}]:[]),{name:title,item:absolute(path)}];const schema:Record<string,unknown>[]=[{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:crumb.map((x,i)=>({'@type':'ListItem',position:i+1,...x}))}];if(p?.kind==='service')schema.push({'@context':'https://schema.org','@type':'Service',name:p.title,description:p.lead,url:absolute(path),provider:{'@id':absolute('/#organisation')},areaServed:['Bayonne','Anglet','Biarritz','Pays Basque']});if(p?.kind==='guide')schema.push({'@context':'https://schema.org','@type':'Article',headline:p.title,description:p.lead,author:{'@type':'Organization',name:site.name},mainEntityOfPage:absolute(path)});
return <main id="main" className="wrap"><nav className="breadcrumbs" aria-label="Fil d’Ariane"><Link href="/">Accueil</Link><ChevronRight size={13}/>{parent&&<><Link href={parent}>{crumb[1].name}</Link><ChevronRight size={13}/></>}<span aria-current="page">{hub?'Ressources & expertises':p?.kicker.split('·')[0]}</span></nav><header className="page-hero"><p className="eyebrow">{p?.kicker||'LES EXPERTISES MISTER IA 64'}</p><h1>{title}</h1><p className="lead">{(p||hub).lead}</p>{p&&['service','solution'].includes(p.kind)&&<div className="hero-actions"><Link className="button" href={'/contact?offre='+(p.price?'diagnostic':'projet')}>{p.price?'Demander mon diagnostic — 99 €':'Parler de mon besoin'}<ArrowUpRight size={18}/></Link><Link className="text-link" href="/methode">Comment nous travaillons</Link></div>}</header>{hub?<div className="hub-grid">{pages.filter(x=>x.kind===hub.kind).map(x=><Link className="hub-card" href={x.path} key={x.path}><p className="eyebrow">{x.kicker}</p><h2>{x.title}</h2><p>{x.lead}</p><span className="text-link">{hub.kind==='guide'?'Lire le guide':'Découvrir le périmètre'}<ArrowUpRight size={17}/></span></Link>)}</div>:<div className="page-body"><article className="article">{p!.sections.map((s,i)=><section id={'section-'+(i+1)} key={s.title}><h2>{s.title}</h2>{s.paragraphs.map(t=><p key={t}>{t}</p>)}{s.items.length>0&&<ul>{s.items.map(t=><li key={t}>{t}</li>)}</ul>}</section>)}{p!.faq.length>0&&<section className="faq"><h2>Vos questions, simplement.</h2>{p!.faq.map(x=><details key={x.q}><summary>{x.q}</summary><p>{x.a}</p></details>)}</section>}{p!.sources.length>0&&<section className="source-list"><h2>Sources et repères</h2>{p!.sources.map(([name,url])=><a href={url} key={url} rel="noopener noreferrer" target="_blank">{name} ↗</a>)}<p>Sources consultées le 8 septembre 2026.</p></section>}<nav className="related" aria-label="Pour aller plus loin">{p!.links.map(href=><Link key={href} href={href}>{findPage(href)?.kicker.split('·')[0]||({'/contact':'PARLONS DE VOTRE BESOIN','/diagnostic':'ESTIMER MON POTENTIEL','/solutions':'VOS BESOINS'} as Record<string,string>)[href]||'Découvrir'}</Link>)}</nav></article><aside className="sidebox"><p className="eyebrow">SUR CETTE PAGE</p>{p!.sections.map((s,i)=><a key={s.title} href={'#section-'+(i+1)}>{s.title}</a>)}<hr className="my-6 border-border"/><h2>Une tâche à examiner ?</h2><p>Commençons par un processus qui vous coûte du temps.</p><Link className="button" href="/contact">En discuter <ArrowUpRight size={16}/></Link></aside></div>}{!path.includes('legales')&&!path.includes('confidentialite')&&<CTA compact/>}{schema.map((s,i)=><script key={i} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(s).replace(/</g,'\u003c')}}/>)}</main>}
